interval: 60s
servers:
- server: 127.0.0.1:1099
  dockerPid: 25643
  queries:
  - java.lang:type=Memory*
  - java.lang:type=GarbageCollector,name=*
  - java.lang:type=MemoryPool,name=*
  - java.lang:type=Runtime
  - java.lang:type=Threading
